name: Run Tests
on: [push]
jobs:
  tests:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
      
      - name: Run Tests
        run: uv run pytest